# # -*- coding: utf-8 -*-
# """Skill Demand and Job Opp Analytics.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/13qcTR8O4kaonp9PYWIP9x0N_oFjrqJJL

# # Import data
# """

# pip install telegram-export

# # STEP 1: Mount Google Drive (including Shared Drives)
# from google.colab import drive
# drive.mount('/content/drive')

# # STEP 2: Read the JSON file from Shared Drive "Agora"
# import json
# import pandas as pd

# # Define the full path to the JSON file
# json_path = '/content/drive/Shared drives/Agora Data Driven/Upwork Research/result.json'

# # Load the JSON file
# with open(json_path, 'r') as f:
#     data = json.load(f)

# # Try converting to a DataFrame if it's tabular
# try:
#     df = pd.DataFrame(data)
#     print("✅ JSON loaded as DataFrame:")
#     display(df.head())
# except:
#     print("ℹ️ JSON is not tabular. Here's the raw data:")
#     print(data)

# """## Data Transformation"""

# # Step 1: Filter messages based on key indicators
# job_posts = [
#     msg for msg in df['messages']
#     if isinstance(msg, dict)
#     and msg.get('type') == 'message'
#     and msg.get('from') == 'Zenfl Upwork Bot'
#     and isinstance(msg.get('text'), list)
#     and any(isinstance(t, dict) and t.get('text', '').lower().startswith('skills') for t in msg['text'] if isinstance(t, dict))
#     and 'inline_bot_buttons' in msg
#     and isinstance(msg['inline_bot_buttons'], list)
#     and len(msg['inline_bot_buttons']) > 0
# ]

# # Step 2: Convert filtered list to DataFrame
# raw_df = pd.DataFrame(job_posts)

# # Step 3: Preview result
# print(f"Found {len(raw_df)} job posts.")
# display(raw_df.head(3))

# import pandas as pd
# import re

# # STEP 1: If 'text' is already parsed, just alias it
# raw_df['parsed_text'] = raw_df['text']

# # STEP 2: Extract fields (with cleaned skills)
# def extract_fields(parsed):
#     job_title = None
#     rate = None
#     skills = None
#     client_info = None
#     description = None
#     timestamp = None
#     category = None

#     rating = None
#     num_reviews = None
#     country = None
#     num_jobs = None
#     hire_rate = None
#     avg_rate = None
#     total_spent = None

#     for i, item in enumerate(parsed):
#         # CATEGORY: Extract string directly after the title
#         if isinstance(item, str) and i > 0 and isinstance(parsed[i - 1], dict) and parsed[i - 1].get('type') == 'bold':
#             if category is None:
#                 match = re.match(r'\s*\n\n(.*?) •', item)
#                 if match:
#                     category = match.group(1)

#         if isinstance(item, dict):
#             if item.get('type') == 'bold':
#                 text = item.get('text', '')
#                 if job_title is None:
#                     job_title = text
#                 elif '$' in text and 'hour' in text.lower():
#                     rate = text
#                 elif text.strip().lower() == 'skills' and i + 1 < len(parsed):
#                     next_item = parsed[i + 1]
#                     if isinstance(next_item, str):
#                         # Clean skills: remove \n and extra whitespace
#                         skills = next_item.replace('\n', '').strip()
#                 elif text.strip().lower() == 'about client' and i + 1 < len(parsed):
#                     client_info = parsed[i + 1] if isinstance(parsed[i + 1], str) else None
#                     if client_info:
#                         rating_match = re.search(r'⭐️ ([\d.]+)', client_info)
#                         reviews_match = re.search(r'• (\d+) reviews', client_info)
#                         country_match = re.search(r'reviews • ([^•\n]+)', client_info)
#                         jobs_match = re.search(r'• (\d+) jobs', client_info)
#                         hire_match = re.search(r'Hire rate (\d+%)', client_info)
#                         avg_rate_match = re.search(r'Average rate \$([\d.]+)', client_info)
#                         spent_match = re.search(r'Spent \$([\d,]+(?:\.\d{2})?)', client_info)

#                         rating = float(rating_match.group(1)) if rating_match else None
#                         num_reviews = int(reviews_match.group(1)) if reviews_match else None
#                         country = country_match.group(1).strip() if country_match else None
#                         num_jobs = int(jobs_match.group(1)) if jobs_match else None
#                         hire_rate = hire_match.group(1) if hire_match else None
#                         avg_rate = float(avg_rate_match.group(1)) if avg_rate_match else None
#                         total_spent = spent_match.group(1) if spent_match else None

#             elif item.get('type') == 'blockquote':
#                 description = item.get('text', '')
#             elif item.get('type') == 'italic' and '⏱️' in item.get('text', ''):
#                 timestamp = item.get('text')

#     return pd.Series({
#         'job_title': job_title,
#         'rate': rate,
#         'Category': category,
#         'skills': skills,
#         'client_info': client_info,
#         'description': description,
#         'timestamp': timestamp,
#         'Rating': rating,
#         'Reviews': num_reviews,
#         'Country': country,
#         'Client Jobs': num_jobs,
#         'Hire Rate': hire_rate,
#         'Avg Rate': avg_rate,
#         'Total Spent': total_spent
#     })

# # STEP 3: Apply extraction
# extracted = raw_df['parsed_text'].apply(extract_fields)
# raw_df = pd.concat([raw_df, extracted], axis=1)

# # STEP 4: Extract Job Link
# def extract_job_link(buttons):
#     if isinstance(buttons, list) and buttons:
#         try:
#             return buttons[0][0]['data']
#         except (IndexError, KeyError, TypeError):
#             return None
#     return None

# raw_df['Job Link'] = raw_df['inline_bot_buttons'].apply(extract_job_link)

# # STEP 5: Final Output
# raw_df = raw_df[['date', 'job_title', 'Category', 'rate', 'skills', 'client_info',
#                         'description', 'timestamp', 'Rating', 'Reviews', 'Country',
#                         'Client Jobs', 'Hire Rate', 'Avg Rate', 'Total Spent', 'Job Link']]

# # Preview
# raw_df.head(20)

# raw_df['description'] = raw_df['description'].str.lower()

# import pandas as pd
# from google.colab import auth
# from google.cloud import bigquery
# import re

# # ✅ Step 1: Authenticate
# auth.authenticate_user()

# # ✅ Step 2: Initialize BigQuery client
# project_id = "agora-data-driven"
# client = bigquery.Client(project=project_id)

# # ✅ Step 3: Define dataset and table
# dataset_id = "upwork"
# table_id = "raw_db"
# table_ref = f"{project_id}.{dataset_id}.{table_id}"

# # ✅ Step 4: Clean column names for BigQuery
# def clean_bq_column(name: str) -> str:
#     name = name.strip()
#     name = re.sub(r'[^A-Za-z0-9_]', '_', name)  # replace invalid chars
#     if not re.match(r'^[A-Za-z_]', name):
#         name = "_" + name
#     return name

# raw_df.columns = [clean_bq_column(col) for col in raw_df.columns]

# # ✅ Step 5: Configure job
# job_config = bigquery.LoadJobConfig(
#     write_disposition="WRITE_TRUNCATE",
#     autodetect=True
# )

# # ✅ Step 6: Upload DataFrame to BigQuery
# try:
#     job = client.load_table_from_dataframe(raw_df, table_ref, job_config=job_config)
#     job.result()
#     print(f"✅ Successfully created/overwritten table at {table_ref}")

#     # Verify
#     table = client.get_table(table_ref)
#     print(f"Table now has {table.num_rows} rows and {len(table.schema)} columns.")
# except Exception as e:
#     print(f"❌ Upload to BigQuery failed: {e}")

# """# Classifier"""

# final_df = raw_df.copy()

# import re

# # Step 1: Define keyword groups
# paralegal_keywords = [
#     "virtual paralegal", "paralegal", "virtual legal assistant", "legal assistant", "litigation support",
#     "legal research", "legal writing", "document review", "legal drafting", "legal transcription",
#     "legal proofreading", "legal memo", "legal opinion", "legal admin support", "contract review",
#     "contract drafting", "contract management", "NDA drafting", "legal service", "law firm",
#     "case law research", "compliance support", "due diligence", "policy drafting", "litigation",
#     "court filings", "legal case management", "legal calendaring", "civil litigation", "legal demand letters",
#     "deposition summaries", "corporate paralegal", "corporate recordkeeping", "bylaws drafting",
#     "legal calendar management", "attorneys", "virtual receptionist"
# ]

# social_keywords = [
#     "social media management", "social media manager", "social media marketing", "social media strategist",
#     "social media content", "social media scheduling", "social media", "instagram", "facebook", "tiktok",
#     "facebook ads", "google ads", "media buyer", "social media managers", "social media marketers",
#     "social media strategists", "social media contents", "social media schedulings", "instagrams", "facebooks",
#     "tiktoks", "facebook ad", "google ad", "media buyers"
# ]

# # Step 2: Compile regex patterns (case-insensitive)
# paralegal_pattern = re.compile(r'\b(?:' + '|'.join(re.escape(w) for w in paralegal_keywords) + r')\b', re.IGNORECASE)
# social_pattern = re.compile(r'\b(?:' + '|'.join(re.escape(w) for w in social_keywords) + r')\b', re.IGNORECASE)

# # Step 3: Define function to assign Job Type
# def classify_job_type(row):
#     combined_text = ' '.join([
#         str(row.get('job_title', '')),
#         str(row.get('description', '')),
#         str(row.get('skills', ''))
#     ])
#     if paralegal_pattern.search(combined_text):
#         return "Paralegal"
#     elif social_pattern.search(combined_text):
#         return "Social Media"
#     else:
#         return None

# # Step 4: Apply classification
# final_df['Job Type'] = final_df.apply(classify_job_type, axis=1)

# # Step 5: Preview
# final_df[['date', 'job_title', 'Job Type']].head()

# """## Social Media Manager"""

# # Step 1: Define Facebook-related keywords
# facebook_keywords = [
#     "facebook", "meta", "fb", "facebook ads", "facebook ad", "facebook campaign",
#     "facebook pixel", "facebook marketing", "facebook page", "facebook manager",
#     "facebook boost", "facebook strategy", "facebook targeting"
# ]

# # Step 2: Compile regex pattern (case-insensitive)
# facebook_pattern = re.compile(r'\b(?:' + '|'.join(re.escape(w) for w in facebook_keywords) + r')\b', re.IGNORECASE)

# # Step 3: Define function to tag Facebook-related jobs with 1/0
# def detect_facebook_binary(row):
#     combined_text = ' '.join([
#         str(row.get('job_title', '')),
#         str(row.get('description', '')),
#         str(row.get('skills', ''))
#     ])
#     return 1 if facebook_pattern.search(combined_text) else 0

# # Step 4: Apply to DataFrame
# final_df["Facebook?"] = final_df.apply(detect_facebook_binary, axis=1)

# # Step 5: Preview
# final_df[['job_title', 'Facebook?']].head()

# # Step 1: Define Instagram-related keywords
# instagram_keywords = [
#     "instagram", "ig", "insta", "instagram ads", "instagram ad", "instagram story",
#     "instagram stories", "instagram reels", "instagram post", "instagram content",
#     "instagram strategy", "instagram page"
# ]

# # Step 2: Compile regex pattern
# instagram_pattern = re.compile(r'\b(?:' + '|'.join(re.escape(w) for w in instagram_keywords) + r')\b', re.IGNORECASE)

# # Step 3: Define detection function for Instagram
# def detect_instagram(row):
#     combined_text = ' '.join([
#         str(row.get('job_title', '')),
#         str(row.get('description', '')),
#         str(row.get('skills', ''))
#     ])
#     return 1 if instagram_pattern.search(combined_text) else 0

# # Step 4: Apply to DataFrame
# final_df["Instagram?"] = final_df.apply(detect_instagram, axis=1)

# # Step 5: Preview
# final_df[['job_title', 'Instagram?']].head()

# # Step 1: Define LinkedIn-related keywords
# linkedin_keywords = [
#     "linkedin", "linked in", "linkedin ads", "linkedin ad", "linkedin campaign",
#     "linkedin marketing", "linkedin content", "linkedin outreach", "linkedin page"
# ]

# # Step 2: Compile regex pattern (case-insensitive)
# linkedin_pattern = re.compile(r'\b(?:' + '|'.join(re.escape(w) for w in linkedin_keywords) + r')\b', re.IGNORECASE)

# # Step 3: Detection function
# def detect_linkedin(row):
#     combined_text = ' '.join([
#         str(row.get('job_title', '')),
#         str(row.get('description', '')),
#         str(row.get('skills', ''))
#     ])
#     return 1 if linkedin_pattern.search(combined_text) else 0

# # Step 4: Apply to DataFrame
# final_df["LinkedIn?"] = final_df.apply(detect_linkedin, axis=1)

# # Step 5: Preview
# final_df[['job_title', 'LinkedIn?']].head()

# # Step 1: Define Email Marketing-related keywords
# email_keywords = [
#     "email marketing", "email campaigns", "email automation", "email flows",
#     "email strategy", "email newsletter", "cold email", "drip campaigns",
#     "mailchimp", "klaviyo", "activecampaign", "convertkit"
# ]

# # Step 2: Compile regex pattern (case-insensitive)
# email_pattern = re.compile(r'\b(?:' + '|'.join(re.escape(w) for w in email_keywords) + r')\b', re.IGNORECASE)

# # Step 3: Detection function
# def detect_email_marketing(row):
#     combined_text = ' '.join([
#         str(row.get('job_title', '')),
#         str(row.get('description', '')),
#         str(row.get('skills', ''))
#     ])
#     return 1 if email_pattern.search(combined_text) else 0

# # Step 4: Apply to DataFrame
# final_df["Email Marketing?"] = final_df.apply(detect_email_marketing, axis=1)

# # Step 5: Preview
# final_df[['job_title', 'Email Marketing?']].head()

# # Step 1: Define Google-related keywords
# google_keywords = [
#     "google", "google ads", "google ad", "google analytics", "google marketing",
#     "google campaign", "google tag manager", "google business",
#     "google search", "google display"
# ]

# # Step 2: Compile regex pattern (case-insensitive)
# google_pattern = re.compile(r'\b(?:' + '|'.join(re.escape(w) for w in google_keywords) + r')\b', re.IGNORECASE)

# # Step 3: Define detection function
# def detect_google(row):
#     combined_text = ' '.join([
#         str(row.get('job_title', '')),
#         str(row.get('description', '')),
#         str(row.get('skills', ''))
#     ])
#     return 1 if google_pattern.search(combined_text) else 0

# # Step 4: Apply to DataFrame
# final_df["Google?"] = final_df.apply(detect_google, axis=1)

# # Step 5: Preview
# final_df[['job_title', 'Google?']].head()

# # Step 1: Define TikTok-related keywords
# tiktok_keywords = [
#     "tiktok", "tik tok", "tiktok ads", "tiktok ad", "tiktok campaign",
#     "tiktok strategy", "tiktok marketing", "tiktok content",
#     "tiktok page", "tiktok growth"
# ]

# # Step 2: Compile regex pattern (case-insensitive)
# tiktok_pattern = re.compile(r'\b(?:' + '|'.join(re.escape(w) for w in tiktok_keywords) + r')\b', re.IGNORECASE)

# # Step 3: Detection function
# def detect_tiktok(row):
#     combined_text = ' '.join([
#         str(row.get('job_title', '')),
#         str(row.get('description', '')),
#         str(row.get('skills', ''))
#     ])
#     return 1 if tiktok_pattern.search(combined_text) else 0

# # Step 4: Apply to DataFrame
# final_df["TikTok?"] = final_df.apply(detect_tiktok, axis=1)

# # Step 5: Preview
# final_df[['job_title', 'TikTok?']].head()

# # Step 1: Define SEO-related keywords
# seo_keywords = [
#     "seo", "search engine optimization", "on-page seo", "off-page seo",
#     "technical seo", "keyword research", "serp", "backlink", "backlinks",
#     "seo tools", "semrush", "ahrefs", "moz", "google search console",
#     "seo audit", "seo content", "seo strategy"
# ]

# # Step 2: Compile regex pattern
# seo_pattern = re.compile(r'\b(?:' + '|'.join(re.escape(w) for w in seo_keywords) + r')\b', re.IGNORECASE)

# # Step 3: Detection function
# def detect_seo(row):
#     combined_text = ' '.join([
#         str(row.get('job_title', '')),
#         str(row.get('description', '')),
#         str(row.get('skills', ''))
#     ])
#     return 1 if seo_pattern.search(combined_text) else 0

# # Step 4: Apply to DataFrame
# final_df["SEO?"] = final_df.apply(detect_seo, axis=1)

# # Step 5: Preview
# final_df[['job_title', 'SEO?']].head()

# """## Automation"""

# # Step 1: Define automation-related keywords
# automation_keywords = [
#     "automation", "zapier", "integromat", "make.com", "make", "automate", "webhook",
#     "workflow automation", "task automation", "automation tools",
#     "process automation", "automated workflow", "automation setup", "api integration",
#     "automation", "workflow automation", "business automation", "process automation", "zapier", "API automation", "webhook", "script automation", "task automation", "robotic process automation", "Python automation", "Power Automate", "Selenium", "Google Apps Script", "batch automation", "browser automation", "email automation", "ecommerce automation", "marketing automation",
#     "sales funnel automation", "data entry automation", "n8n", "zapier", "make.com", 'app script'
# ]

# # Step 2: Compile regex pattern (case-insensitive)
# automation_pattern = re.compile(r'\b(?:' + '|'.join(re.escape(w) for w in automation_keywords) + r')\b', re.IGNORECASE)

# # Step 3: Detection function
# def detect_automation(row):
#     combined_text = ' '.join([
#         str(row.get('job_title', '')),
#         str(row.get('description', '')),
#         str(row.get('skills', ''))
#     ])
#     return 1 if automation_pattern.search(combined_text) else 0

# # Step 4: Apply to DataFrame
# final_df["Automation?"] = final_df.apply(detect_automation, axis=1)

# # Step 5: Preview
# final_df[['job_title', 'Automation?']].head()

# import re

# # Step 1: Define Make.com-related keywords
# make_keywords = [
#     "make.com", "make (integromat)", "integromat", "make automation", "make workflow",
#     "make scenario", "make zapier", "make integration"
# ]

# # Step 2: Compile regex pattern (case-insensitive)
# make_pattern = re.compile(r'\b(?:' + '|'.join(re.escape(w) for w in make_keywords) + r')\b', re.IGNORECASE)

# # Step 3: Define detection function
# def detect_make(row):
#     combined_text = ' '.join([
#         str(row.get('job_title', '')),
#         str(row.get('description', '')),
#         str(row.get('skills', ''))
#     ])
#     return 1 if make_pattern.search(combined_text) else 0

# # Step 4: Apply to DataFrame
# final_df["Make.com?"] = final_df.apply(detect_make, axis=1)

# # Step 5: Preview
# final_df[['job_title', 'Make.com?']].head()

# import re

# # Step 1: Define n8n-related keywords
# n8n_keywords = [
#     "n8n", "n8n.io", "n8n workflow", "n8n automation", "n8n integration", "n8n scenario"
# ]

# # Step 2: Compile regex pattern (case-insensitive)
# n8n_pattern = re.compile(r'\b(?:' + '|'.join(re.escape(w) for w in n8n_keywords) + r')\b', re.IGNORECASE)

# # Step 3: Define detection function
# def detect_n8n(row):
#     combined_text = ' '.join([
#         str(row.get('job_title', '')),
#         str(row.get('description', '')),
#         str(row.get('skills', ''))
#     ])
#     return 1 if n8n_pattern.search(combined_text) else 0

# # Step 4: Apply to DataFrame
# final_df["n8n?"] = final_df.apply(detect_n8n, axis=1)

# # Step 5: Preview
# final_df[['job_title', 'n8n?']].head()

# import re

# # Step 1: Define Google Apps Script and Google Sheets-related keywords
# gsheet_keywords = [
#     "google sheets", "google sheet", "google spreadsheet", "google spreadsheets",
#     "apps script", "google apps script", "gas", "gscript", "google script",
#     "gsheet", "g sheet", "g spreadsheet","app script", "appscript"
# ]

# # Step 2: Compile regex pattern (case-insensitive)
# gsheet_pattern = re.compile(r'\b(?:' + '|'.join(re.escape(w) for w in gsheet_keywords) + r')\b', re.IGNORECASE)

# # Step 3: Define detection function
# def detect_gsheet(row):
#     combined_text = ' '.join([
#         str(row.get('job_title', '')),
#         str(row.get('description', '')),
#         str(row.get('skills', ''))
#     ])
#     return 1 if gsheet_pattern.search(combined_text) else 0

# # Step 4: Apply to DataFrame
# final_df["Google Sheets / Apps Script?"] = final_df.apply(detect_gsheet, axis=1)

# # Step 5: Preview
# final_df[['job_title', 'Google Sheets / Apps Script?']].head()

# import re

# # Step 1: Define Zapier-related keywords
# zapier_keywords = [
#     "zapier", "zap", "zapier automation", "zapier integration", "zapier workflow"
# ]

# # Step 2: Compile regex pattern (case-insensitive)
# zapier_pattern = re.compile(r'\b(?:' + '|'.join(re.escape(w) for w in zapier_keywords) + r')\b', re.IGNORECASE)

# # Step 3: Define detection function
# def detect_zapier(row):
#     combined_text = ' '.join([
#         str(row.get('job_title', '')),
#         str(row.get('description', '')),
#         str(row.get('skills', ''))
#     ])
#     return 1 if zapier_pattern.search(combined_text) else 0

# # Step 4: Apply to DataFrame
# final_df["Zapier?"] = final_df.apply(detect_zapier, axis=1)

# # Step 5: Preview
# final_df[['job_title', 'Zapier?']].head()

# import re

# # Step 1: Define Go High Level-related keywords
# ghl_keywords = [
#     "go high level", "gohighlevel", "gohigh level", "ghl", "ghl crm", "highlevel crm",
#     "gohighlevel automation", "gohighlevel workflow", "gohighlevel integration"
# ]

# # Step 2: Compile regex pattern (case-insensitive)
# ghl_pattern = re.compile(r'\b(?:' + '|'.join(re.escape(w) for w in ghl_keywords) + r')\b', re.IGNORECASE)

# # Step 3: Define detection function
# def detect_ghl(row):
#     combined_text = ' '.join([
#         str(row.get('job_title', '')),
#         str(row.get('description', '')),
#         str(row.get('skills', ''))
#     ])
#     return 1 if ghl_pattern.search(combined_text) else 0

# # Step 4: Apply to DataFrame
# final_df["GoHighLevel?"] = final_df.apply(detect_ghl, axis=1)

# # Step 5: Preview
# final_df[['job_title', 'GoHighLevel?']].head()

# """## Legal Assistant"""

# # Step 1: Define Paralegal-related keywords
# paralegal_keywords = [
#     "paralegal", "virtual paralegal", "corporate paralegal",
#     "legal assistant", "virtual legal assistant",
#     "legal admin support", "legal case management",
#     "legal calendaring", "legal admin", "legal support"
# ]

# # Step 2: Compile regex pattern (case-insensitive)
# paralegal_pattern = re.compile(
#     r'\b(?:' + '|'.join(re.escape(w) for w in paralegal_keywords) + r')\b',
#     re.IGNORECASE
# )

# # Step 3: Define function to tag Paralegal-related jobs with 1/0
# def detect_paralegal(row):
#     combined_text = ' '.join([
#         str(row.get('job_title', '')),
#         str(row.get('description', '')),
#         str(row.get('skills', ''))
#     ])
#     return 1 if paralegal_pattern.search(combined_text) else 0

# # Step 4: Apply to DataFrame
# final_df["Paralegal?"] = final_df.apply(detect_paralegal, axis=1)

# # Step 5: Preview result
# final_df[['job_title', 'Paralegal?']].head()

# # Step 1: Define Legal Research-related keywords
# legal_research_keywords = [
#     "legal research", "case law research", "policy research",
#     "compliance research", "statutory research", "regulatory research",
#     "legal analysis", "case research", "legal opinions", "legal memo", "jurisprudence"
# ]

# # Step 2: Compile regex pattern (case-insensitive)
# legal_research_pattern = re.compile(
#     r'\b(?:' + '|'.join(re.escape(w) for w in legal_research_keywords) + r')\b',
#     re.IGNORECASE
# )

# # Step 3: Define function to tag Legal Research-related jobs with 1/0
# def detect_legal_research(row):
#     combined_text = ' '.join([
#         str(row.get('job_title', '')),
#         str(row.get('description', '')),
#         str(row.get('skills', ''))
#     ])
#     return 1 if legal_research_pattern.search(combined_text) else 0

# # Step 4: Apply to DataFrame
# final_df["Legal Research?"] = final_df.apply(detect_legal_research, axis=1)

# # Step 5: Preview result
# final_df[['job_title', 'Legal Research?']].head()

# # Step 1: Define Legal Admin-related keywords
# legal_admin_keywords = [
#     "admin", "legal admin", "legal administrative support", "legal admin support",
#     "legal assistant", "legal calendaring", "case management",
#     "legal case management", "legal scheduling", "legal document management",
#     "legal operations", "legal clerk", "virtual legal assistant",
#     "virtual legal admin", "legal file management"
# ]

# # Step 2: Compile regex pattern (case-insensitive)
# legal_admin_pattern = re.compile(
#     r'\b(?:' + '|'.join(re.escape(w) for w in legal_admin_keywords) + r')\b',
#     re.IGNORECASE
# )

# # Step 3: Define function to tag Legal Admin-related jobs with 1/0
# def detect_legal_admin(row):
#     combined_text = ' '.join([
#         str(row.get('job_title', '')),
#         str(row.get('description', '')),
#         str(row.get('skills', ''))
#     ])
#     return 1 if legal_admin_pattern.search(combined_text) else 0

# # Step 4: Apply to DataFrame
# final_df["Legal Admin?"] = final_df.apply(detect_legal_admin, axis=1)

# # Step 5: Preview result
# final_df[['job_title', 'Legal Admin?']].head()

# # Step 1: Define Corporate Law-related keywords
# corporate_law_keywords = [
#     "corporate law", "corporate paralegal", "corporate recordkeeping",
#     "bylaws drafting", "corporate governance", "corporate compliance",
#     "board resolutions", "shareholder agreements", "corporate secretary",
#     "entity formation", "corporate filings", "corporate legal",
#     "corporate structure", "mergers and acquisitions", "m&a"
# ]

# # Step 2: Compile regex pattern (case-insensitive)
# corporate_law_pattern = re.compile(
#     r'\b(?:' + '|'.join(re.escape(w) for w in corporate_law_keywords) + r')\b',
#     re.IGNORECASE
# )

# # Step 3: Define function to tag Corporate Law-related jobs with 1/0
# def detect_corporate_law(row):
#     combined_text = ' '.join([
#         str(row.get('job_title', '')),
#         str(row.get('description', '')),
#         str(row.get('skills', ''))
#     ])
#     return 1 if corporate_law_pattern.search(combined_text) else 0

# # Step 4: Apply to DataFrame
# final_df["Corporate Law?"] = final_df.apply(detect_corporate_law, axis=1)

# # Step 5: Preview result
# final_df[['job_title', 'Corporate Law?']].head()

# real_estate_keywords = [
#     # General terms
#     "real estate", "real property", "property law", "real estate law", "property transactions",
#     "real estate transactions", "property management", "real estate paralegal",
#     "real estate assistant", "real estate legal assistant", "real estate support",

#     # Contracts / documents
#     "real estate contract", "real estate contracts", "real estate agreements",
#     "purchase agreement", "sales agreement", "lease agreement", "leasing contract",
#     "deed", "deed preparation", "deed drafting", "deed of trust", "mortgage agreement",

#     # Closing / title
#     "closing documents", "real estate closing", "property closing", "escrow",
#     "title search", "title review", "title insurance", "closing coordination",

#     # Compliance / regulatory
#     "property compliance", "real estate compliance", "zoning", "land use",
#     "real estate regulatory", "building code", "real estate permits",

#     # Other tasks
#     "escrow coordination", "real estate filing", "real estate filing support",
#     "real estate due diligence", "real estate transactions support", "real estate litigation"
# ]

# # Step 1: Compile regex pattern
# real_estate_pattern = re.compile(
#     r'\b(?:' + '|'.join(re.escape(w) for w in real_estate_keywords) + r')\b',
#     re.IGNORECASE
# )

# # Step 2: Detection function
# def detect_real_estate(row):
#     combined_text = ' '.join([
#         str(row.get('job_title', '')),
#         str(row.get('description', '')),
#         str(row.get('skills', ''))
#     ])
#     return 1 if real_estate_pattern.search(combined_text) else 0

# # Step 3: Apply
# final_df["Real Estate?"] = final_df.apply(detect_real_estate, axis=1)

# # Step 4: Preview
# final_df[['job_title', 'Real Estate?']].head()

# """## Data Science"""

# import re

# # Step 1: Define Data Science-related keywords
# data_science_keywords = [
#     "data science", "machine learning", "analytics", "classification",
#     "regression", "data visualization", "powerbi", "lookerstudio", "looker studio","data studio", "tableau",
#     "google sheets", "excel", "data analysis", "predictive modeling", "big data",
#     "artificial intelligence", "deep learning", "neural networks", "supervised learning",
#     "unsupervised learning", "feature engineering", "data wrangling", "data pipelines"
# ]

# # Step 2: Compile regex pattern (case-insensitive)
# data_science_pattern = re.compile(
#     r'\b(?:' + '|'.join(re.escape(w) for w in data_science_keywords) + r')\b',
#     re.IGNORECASE
# )

# # Step 3: Define function to tag Data Science-related jobs with 1/0
# def detect_data_science(row):
#     combined_text = ' '.join([  # Combine the relevant columns (job_title, description, skills)
#         str(row.get('job_title', '')),
#         str(row.get('description', '')),
#         str(row.get('skills', ''))
#     ])
#     return 1 if data_science_pattern.search(combined_text) else 0

# # Step 4: Apply to DataFrame
# final_df["Data Science?"] = final_df.apply(detect_data_science, axis=1)

# # Step 5: Preview result
# final_df[['job_title', 'Data Science?']].head()

# import re

# # Step 1: Define Data Visualization-related keywords
# data_visualization_keywords = [
#     "data visualization", "tableau", "powerbi","power bi",  "looker studio", "lookerstudio" "data dashboard",
#     "dashboard", "visualization", "chart", "graph", "interactive dashboard",
#     "business intelligence", "BI tools", "reporting tools", "data storytelling"
# ]

# # Step 2: Compile regex pattern (case-insensitive)
# data_visualization_pattern = re.compile(
#     r'\b(?:' + '|'.join(re.escape(w) for w in data_visualization_keywords) + r')\b',
#     re.IGNORECASE
# )

# # Step 3: Define function to tag Data Visualization-related jobs with 1/0
# def detect_data_visualization(row):
#     combined_text = ' '.join([  # Combine the relevant columns (job_title, description, skills)
#         str(row.get('job_title', '')),
#         str(row.get('description', '')),
#         str(row.get('skills', ''))
#     ])
#     return 1 if data_visualization_pattern.search(combined_text) else 0

# # Step 4: Apply to DataFrame
# final_df["Data Visualization?"] = final_df.apply(detect_data_visualization, axis=1)

# # Step 5: Preview result
# final_df[['job_title', 'Data Visualization?']].head()

# """# Skill Analytics"""

# from collections import Counter

# def count_skills(skills_series):
#     skill_counter = Counter()

#     for entry in skills_series.dropna():
#         skills = [s.strip() for s in entry.split('•') if s.strip()]
#         skill_counter.update(skills)

#     return pd.DataFrame(skill_counter.items(), columns=['Skill', 'Count']).sort_values(by='Count', ascending=False).reset_index(drop=True)

# # Apply the function to final_df['skills']
# skill_counts_df = count_skills(final_df['skills'])

# # Preview top skills
# skill_counts_df.head(26)

# Automation_df = final_df[final_df["Automation?"] == 1]
# Automation_df["description"]

# import pandas as pd
# from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
# from collections import Counter
# import re

# # Step 1: Prepare stopwords
# stopwords = set(ENGLISH_STOP_WORDS)

# # Step 2: Clean and process text
# def process_description(desc):
#     # Lowercase and remove non-alphabetic characters
#     words = re.findall(r'\b[a-z]{2,}\b', str(desc).lower())
#     # Remove stopwords and return unique words per row
#     return set(word for word in words if word not in stopwords)

# # Step 3: Apply processing to each row
# unique_words_per_row = Automation_df["description"].apply(process_description)

# # Step 4: Count each word only once per row using Counter
# word_counter = Counter()
# for word_set in unique_words_per_row:
#     word_counter.update(word_set)

# # Step 5: Get most common words
# most_common_words = word_counter.most_common(2000)

# # Display result
# for word, count in most_common_words:
#     print(f"{word}: {count}")

# import numpy as np

# if "Hire_Rate" in final_df.columns:
#     final_df["Hire_Rate"] = (
#         final_df["Hire_Rate"]
#         .astype(str)                              # make everything string first
#         .str.replace("%", "", regex=False)        # remove %
#         .replace(["None", "nan", ""], np.nan)     # turn bad strings into NaN
#     )
#     final_df["Hire_Rate"] = pd.to_numeric(final_df["Hire_Rate"], errors="coerce") / 100.0

# """# Data Cleaning"""

# final_df

# """# Export Data"""

# import pandas as pd
# from google.colab import auth
# from google.cloud import bigquery
# import re

# # ✅ Step 1: Authenticate
# auth.authenticate_user()

# # ✅ Step 2: Initialize BigQuery client
# project_id = "agora-data-driven"
# client = bigquery.Client(project=project_id)

# # ✅ Step 3: Define dataset and table
# dataset_id = "upwork"          # dataset inside your project
# table_id = "full_db"           # name of the table to create
# table_ref = f"{project_id}.{dataset_id}.{table_id}"

# # ✅ Step 4: Clean column names for BigQuery
# def clean_bq_column(name: str) -> str:
#     name = name.strip()
#     # Replace all invalid chars (anything not A-Z, a-z, 0-9, or _) with underscore
#     name = re.sub(r'[^A-Za-z0-9_]', '_', name)
#     # Ensure starts with letter or underscore
#     if not re.match(r'^[A-Za-z_]', name):
#         name = "_" + name
#     return name

# final_df.columns = [clean_bq_column(col) for col in final_df.columns]

# # ✅ Step 5: Configure job
# job_config = bigquery.LoadJobConfig(
#     write_disposition="WRITE_TRUNCATE",   # overwrite each run
#     autodetect=True                       # automatically infer schema from DataFrame
# )

# # ✅ Step 6: Upload DataFrame to BigQuery
# try:
#     job = client.load_table_from_dataframe(final_df, table_ref, job_config=job_config)
#     job.result()  # wait until complete
#     print(f"✅ Successfully created/overwritten table at {table_ref}")

#     # Optional: check row count after upload
#     table = client.get_table(table_ref)
#     print(f"Table now has {table.num_rows} rows and {len(table.schema)} columns.")
# except Exception as e:
#     print(f"❌ Upload to BigQuery failed: {e}")

# final_df.info()