"""Seed a LOCAL portal for click-through testing (no GCP, no ADC).

Run by run_local.ps1 after pointing REGISTRY_LOCAL_DIR + WORKSPACE_LOCAL_DIR at a throwaway folder.
It builds a portal you can actually log into on your laptop:

  * riverdance -- the full demo workspace (seed_workspace) + a known password, so you can see a
    single-client login drop STRAIGHT onto the company overview (/w/riverdance/overview).
  * five more clients (Honey Tribe, Melo Yelo, Rooming House Expert, ASL Logistics, The Contract Shop) onboarded via onboard_client, each with a
    starter workspace + known password, to compare against.

Every client here gets a DISTINCT password on purpose: portal login matches a password to a client
(the email is only a label), so each password must be unique. These are LOCAL dev passwords only --
never used in production. Reruns are safe (every step refuses to clobber existing data).
"""

import sys

import onboard_client
import seed_workspace
import service_templates
import store
import workspace

# (key, display name, LOCAL dev password). Riverdance reuses the rich demo workspace; the rest get a
# clean starter workspace from onboard_client.
DEMO_KEY = "riverdance"
DEMO_NAME = "Riverdance RV Resort"
DEMO_PW = "riverdance-demo"

OTHER_CLIENTS = [
    ("honeytribe", "Honey Tribe", "honeytribe-demo"),
    ("meloyelo", "Melo Yelo", "meloyelo-demo"),
    ("rhe", "Rooming House Expert", "rhe-demo"),
    ("asllogistics", "ASL Logistics", "asllogistics-demo"),
    ("contractshop", "The Contract Shop", "contractshop-demo"),
]


# Operator accounts (email + password) for the login-mode preview.
#  * info@agoradatadriven.com is THE super admin (can create/manage admin accounts). It's also the
#    identity the no-password preview auto-signs you in as, so Profile + admin management line up.
#  * dev@localhost is a regular admin, seeded so the Accounts list shows both tiers to play with.
SUPER_ADMIN_EMAIL = "info@agoradatadriven.com"
SUPER_ADMIN_PW = "agora-super"
ADMIN_EMAIL = "dev@localhost"
ADMIN_PW = "dev-admin"

# The real Agora team (mirrors the production accounts roster), seeded as ACTIVE admin accounts so
# the Task Board's lead / support / sub-task-owner pickers are populated exactly like production
# (the roster = active admin accounts -- see main._team_roster). Local dev passwords only.
TEAM = [
    ("charles@100.digital", "Charles"),
    ("christian@agoradatadriven.com", "Christian"),
    ("ehjay@agoradatadriven.com", "Ehjay"),
    ("ian@100.digital", "Ian"),
    ("jerome@agoradatadriven.com", "Jerome"),
    ("john@bidbrain.com", "John"),
    ("justine@agoradatadriven.com", "Justine"),
    ("lance@agoradatadriven.com", "Lance"),
    ("nico@agoradatadriven.com", "Nico"),
    ("paulo@agoradatadriven.com", "Paulo"),
    ("samuel@agoradatadriven.com", "Samuel"),
    ("zhen@100.digital", "Zhen"),
]

# Demo tasks for the Delivery -> Task Board (per client key). Each entry is (fields, spec, comments):
#   * fields -- the service card fields (title = the campaign/service name, department, lead/support,
#     priority, dates, client-facing note, etc.). `labels` are NOT set -- the card label is
#     auto-derived from the department. `content_type` is filled from the service template.
#   * spec   -- how the two-level breakdown is built, EXACTLY as the New-Service form does it:
#       svc     = a service_templates key (the "Service type"); its phases + steps (each with a
#                 "done when") are generated by service_templates.build_maintasks.
#       params  = per-service tweaks (e.g. {"qty": 5} supporting blogs, {"tool": "Looker Studio"}).
#       ad      = ad-production sets for a Google/Meta campaign: [(type, qty), ...].
#       done    = how many leading sub-tasks are already ticked ("all" = the whole breakdown), so a
#                 launched/closed card reads complete and an in-process one shows real progress.
#       hold    = optional internal reason -> the card is put on hold (client sees a plain "Paused").
#   * comments -- (sender, name, body, kind) rows; kind "changes" is an open client change request.
# Real campaigns/deliverables so the board reads like the approved prototype, not lorem.
_T = "@agoradatadriven.com"
DEMO_TASKS = {
    "riverdance": [
        ({"title": "Park & Porch | Leads", "stage": "launched", "department": "acquisition",
          "lead_id": "zhen@100.digital", "support_ids": ["ehjay" + _T, "lance" + _T],
          "priority": "High", "due_date": "2026-07-18", "client_facing": True,
          "client_note": "Your campaign is live — first leads are coming through. We're watching cost-per-lead this week before scaling.",
          "deliverable_url": "https://drive.google.com/", "internal_notes": "Watching CPL closely before we scale spend."},
         {"svc": "google_meta_campaign", "ad": [("static", 4)], "done": "all"},
         [("agora", "Zhen", "Campaign's live and the first leads are in — we'll report back on CPL Friday.", "comment")]),
        ({"title": "Direct Booking (Campspot)", "stage": "in_process", "department": "development",
          "lead_id": "nico" + _T, "support_ids": ["jerome" + _T],
          "priority": "Medium", "due_date": "2026-07-20", "client_facing": True,
          "client_note": "Waiting on write access to your tag manager — we'll confirm once it's granted.",
          "internal_notes": "GTM is read-only — write access requested; Daniela to confirm."},
         {"svc": "tracking_setup", "done": 2},
         []),
    ],
    "contractshop": [
        ({"title": "TCS — July reporting", "stage": "for_launch", "department": "data",
          "lead_id": "ian@100.digital", "support_ids": ["samuel" + _T],
          "priority": "High", "due_date": "2026-07-15", "client_facing": True,
          "client_note": "Your July report is ready for a look — we'll walk you through it on the next call.",
          "internal_notes": "Double-check the logo before this goes near the client."},
         {"svc": "dashboard_build", "params": {"tool": "Looker Studio"}, "done": "all"},
         [("agora", "Ian", "July report is ready for your review — anything you'd like added before the call?", "comment")]),
        ({"title": "Get Clients (5 Unexpected Ways)", "stage": "in_process", "department": "acquisition",
          "lead_id": "justine" + _T, "support_ids": ["ehjay" + _T],
          "priority": "Medium", "due_date": "2026-07-21",
          "internal_notes": "Copy-led; the diagnostic quiz is the CTA."},
         {"svc": "google_meta_campaign", "ad": [("static", 6)], "done": 2},
         []),
        ({"title": "TCS — June recap", "stage": "closed", "department": "data",
          "lead_id": "ian@100.digital", "priority": "Medium", "client_facing": True,
          "client_note": "Signed off and filed — thank you!", "deliverable_url": "https://drive.google.com/"},
         {"svc": "dashboard_build", "params": {"tool": "Looker Studio"}, "done": "all"},
         [("client", "Client", "Looks great, approved!", "comment")]),
    ],
    "honeytribe": [
        ({"title": "New Arrivals", "stage": "for_launch", "department": "lifecycle",
          "lead_id": "paulo" + _T, "support_ids": ["charles@100.digital"],
          "priority": "High", "due_date": "2026-07-16", "client_facing": True,
          "client_note": "First New Arrivals posts are in your workspace for approval — let us know if you'd like any tweaks.",
          "deliverable_url": "https://drive.google.com/",
          "internal_notes": "Client leans hard on UGC / BTS — keep it native."},
         {"svc": "organic_social", "params": {"qty": 2, "channel": "Instagram"}, "done": "all"},
         [("agora", "Paulo", "First New Arrivals cut is up for your approval.", "comment"),
          ("client", "Linda", "Can we swap the second clip for a guest testimonial?", "changes")]),
        ({"title": "Buzzbassador research", "stage": "in_process", "department": "data",
          "lead_id": "charles@100.digital", "support_ids": ["ian@100.digital"],
          "priority": "Low", "due_date": "2026-07-24",
          "internal_notes": "Ask Linda what we actually need on Buzzbassador."},
         {"svc": "market_research", "done": 2},
         []),
    ],
    "meloyelo": [
        ({"title": "Q Card — Finance Page", "stage": "in_process", "department": "acquisition",
          "lead_id": "lance" + _T, "support_ids": ["justine" + _T],
          "priority": "Urgent", "due_date": "2026-07-27", "client_facing": True,
          "client_note": "Paused until Jul 24 at your request — we'll pick this back up right after.",
          "internal_notes": "Confirm the hold is lifted before launching."},
         {"svc": "google_meta_campaign", "ad": [("static", 2)], "done": 1,
          "hold": "Client paused until Jul 24."},
         []),
        ({"title": "Finance Page — Meta Pixel + CAPI", "stage": "in_process", "department": "development",
          "lead_id": "samuel" + _T, "support_ids": ["christian" + _T, "john@bidbrain.com"],
          "priority": "High", "due_date": "2026-07-17",
          "internal_notes": "Blocked on access — waiting on Andy, and Imran's reply on the Offroad page."},
         {"svc": "tracking_setup", "done": 1},
         []),
    ],
    "rhe": [
        ({"title": "Negative Gearing", "stage": "in_process",
          "department": "lifecycle", "lead_id": "zhen@100.digital", "support_ids": ["paulo" + _T],
          "priority": "High", "due_date": "2026-07-18", "client_facing": True,
          "client_note": "Anchor blog is drafted and in review — supporting pieces are next.",
          "deliverable_url": "https://drive.google.com/",
          "internal_notes": "Apply Stuart's voice notes from the last batch."},
         {"svc": "content_cycle", "params": {"qty": 5}, "done": 3},
         [("agora", "Zhen", "Anchor blog is drafted — take a look when you have a moment.", "comment")]),
        ({"title": "Rent to Rent", "stage": "in_process", "department": "acquisition",
          "lead_id": "ehjay" + _T, "support_ids": ["justine" + _T],
          "priority": "Medium", "due_date": "2026-07-18",
          "internal_notes": "Blocked on scripts — chase Stuart."},
         {"svc": "google_meta_campaign", "ad": [("video", 3)], "done": 0},
         []),
    ],
    "asllogistics": [
        ({"title": "ASL — onboarding research", "stage": "in_process", "department": "data",
          "lead_id": "charles@100.digital", "support_ids": ["ian@100.digital"],
          "priority": "Medium", "due_date": "2026-07-17", "client_facing": True,
          "client_note": "The research package is underway — you'll get the prioritized findings shortly.",
          "internal_notes": "New client — keep recommendations prioritized, light on jargon."},
         {"svc": "market_research", "done": 3},
         []),
    ],
}


def _seed_tasks():
    """Fill each demo workspace's Task Board once (skipped when it already has tasks).

    Each service is built EXACTLY as the New-Service form does it: the `svc` template + params +
    ad-production generate the two-level maintasks (with a "done when" per step), then we assign
    owners round-robin across the lead + support and tick the leading `done` sub-tasks so each card
    reads at a believable stage.
    """
    for key, entries in DEMO_TASKS.items():
        ws = workspace.load_workspace(key)
        if ws is None or ws.get("tasks"):
            continue  # no workspace yet, or already seeded -- never clobber
        for fields, spec, comments in entries:
            f = dict(fields)
            svc = spec.get("svc")
            tpl = service_templates.get(svc) if svc else None
            if tpl:
                f["content_type"] = tpl["content_type"]
                f["maintasks"] = service_templates.build_maintasks(
                    svc, spec.get("params") or {}, spec.get("ad") or [],
                    id_factory=workspace._new_id)
            task = workspace.add_task(key, f, actor=SUPER_ADMIN_EMAIL)
            mains = task.get("maintasks") or []
            # Owners round-robin across the lead + support, so the Tasks tab shows real avatars.
            roster = [r for r in ([f.get("lead_id", "")] + list(f.get("support_ids") or [])) if r]
            for i, m in enumerate(mains):
                if roster:
                    workspace.set_maintask_owner(key, task["id"], m["id"], roster[i % len(roster)])
            # Progress: tick the leading N sub-tasks ("all" = the whole breakdown).
            flat = [s for m in mains for s in (m.get("subs") or [])]
            want = spec.get("done", 0)
            n_done = len(flat) if want == "all" else min(int(want or 0), len(flat))
            for s in flat[:n_done]:
                workspace.set_subtask_done(key, task["id"], s["id"], True)
            if spec.get("hold"):
                workspace.set_task_hold(key, task["id"], True, spec["hold"], actor=SUPER_ADMIN_EMAIL)
            for sender, name, body, kind in comments:
                workspace.add_task_comment(key, task["id"], sender, name, body, kind=kind)


def main():
    creds = []

    # Seed the operator accounts (idempotent: never clobbers a password you later change).
    store.ensure_super_admin_account(SUPER_ADMIN_EMAIL, SUPER_ADMIN_PW, name="Agora Data Driven")
    store.ensure_admin_account(ADMIN_EMAIL, ADMIN_PW, name="Dev Admin")
    # The real team as active admins -- populates the Task Board's assign pickers like production.
    for email, name in TEAM:
        store.ensure_admin_account(email, "%s-dev" % name.lower(), name=name)

    # Riverdance: rich demo workspace (refuses to clobber) + registry entry + a known password.
    if not workspace.workspace_exists(DEMO_KEY):
        seed_workspace.seed()  # writes workspace/riverdance.json and registers the client
    store.add_client(DEMO_KEY, DEMO_NAME)
    store.set_client_password(DEMO_KEY, DEMO_PW)
    creds.append((DEMO_KEY, DEMO_PW))

    # The other three via the one-step onboarding flow.
    for key, name, pw in OTHER_CLIENTS:
        onboard_client.onboard(key, name, pw)
        creds.append((key, pw))

    # Fill the Delivery -> Task Board with realistic work (skips workspaces that already have tasks).
    _seed_tasks()

    print("\n  Local portal seeded. Log in at http://localhost:8080/login")
    print("  SUPER ADMIN (manages admins; this is 'you'):")
    print("    %-24s  password: %s" % (SUPER_ADMIN_EMAIL, SUPER_ADMIN_PW))
    print("  ADMIN (sees every client):")
    print("    %-24s  password: %s" % (ADMIN_EMAIL, ADMIN_PW))
    print("\n  CLIENT logins -- use ANY email (e.g. owner@example.com) + one of these passwords:\n")
    for key, pw in creds:
        only = " <- single-client: lands straight on the overview" if key == DEMO_KEY else ""
        print("    %-12s  password: %s%s" % (key, pw, only))
    print("")
    return 0


if __name__ == "__main__":
    sys.exit(main())
